version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  test-day-1:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python ./py/test/test_day1.py
          name: Test Day 1

workflows:
  main:
    jobs:
      - test-day-1
